public enum MenuOperacoes {
    CADASTRAR (1),
    CADASTRAR_CLIENTEPFPJ(11),
    CADASTRAR_VEICULO(12),
    CADASTRAR_SEGURO(13),
    CADASTRAR_CONDUTOR(14),
    CADASTRAR_SINISTRO(15),
    VOLTAR_CADASTRAR(10),

    LISTAR(2),
    LISTAR_CLIENTE(21),
    LISTAR_SEGUROS_SEGURADORA(22),
    LISTAR_SEGUROS_CLIENTE(23),
    LISTAR_SINISTROS_CLIENTE(24),
    LISTAR_VEICULO_CLIENTE(25),
    LISTAR_CONDUTORES(26),
    VOLTAR_LISTAR(20),

    EXCLUIR (3),
    EXCLUIR_CLIENTE(31),
    EXCLUIR_VEICULO(32),
    EXCLUIR_SINISTRO(33),
    EXCLUIR_CONDUTOR(34),
    EXCLUIR_SEGURO(35),
    VOLTAR_EXCLUIR(30),

    CONFIGURACOES_SEGURADORA(4),
    CADASTRAR_SEGURADORA(41),
    REMOVER_SEGURADORA(42),
    TROCAR_SEGURADORA(43),
    CALCULAR_RECEITA(44),
    VOLTAR_CONFIGURACOES(40),

    SAIR (0),

    MENU_PRINCIPAL(100),
    MENU_CADASTROS(101),
    MENU_LISTAR(102),
    MENU_EXCLUIR(103),
    MENU_TIPOCLIENTE(104),
    MENU_CONFIGURACOES_SEGURADORA(105);

    public final int operacao ;
    
    MenuOperacoes (int operacao){
        this.operacao = operacao ;
    }
    public int getOperacao (){
        return this.operacao ;
    }
}
